### PR TITLE
Relative uris

### PR DESCRIPTION
**Pull request by mf59816**
Since requests (at least in snap) contain only path, query, and fragment, I would like to have parser and serializer functions that give me that.

1. If you are generally ok with the idea, I will can test cases.
2. Not sure about the name.  I think `relative` is for rootless paths.  Is there a better technical term for schema-and-authority-free urls?

thanks,
m.

### CODE REVIEW

**Comment by mf59816** [comment]
Oh, and note that I have based this branch on `lens`.  Merge with care!

**Comment by MichaelXavier** [comment]
I looked at RFC3986 and indeed relative URIs are a thing, but they are called "relative-ref" now. Just search this document for "relative-ref": https://www.ietf.org/rfc/rfc3986.txt

It feels awkward to me to have to supply information you potentially don't have (authority/scheme) to use a relative parser when the spec says it can stand on its own, so here's what I recommend:

1. Review the lens branch and if everything looks good, I'll
   merge. Merge that into your branch so you have an up-to-date field
   naming scheme.
2. Add a `RelativeRef` type to the `URI.ByteString.Types` module and
   export it from `URI.ByteString`.
3. Have your parser parse that type and remove any extraneous
   arguments.
4. Have `uriParser` be implemented in terms of this `relativeRef`
   parser like you do now and just have it pull apart the
   `RelativeRef` and build a `URI` with it.
5. Update the serialize functions in this same way.
6. Add a few tests and a benchmark for the new code.

**Comment by mf59816** [comment]
Great, I'll do that.  Thanks for doing the research for me!  :-)

**Comment by MichaelXavier** [comment]
Oh and just a heads up in case you got started, I was a bit hasty with the lens branch and pushed the change before discussing it with my team. I've got sign off with what you'll see on lens right now: the lens module isn't exported, all type fields don't have the _ in them. All lenses are postfixed with L.

**Comment by mf59816** [comment]
Yes, I was briefly confused by that, but now I'm rebased on 74fc43f1.  Thanks!  I like that better, too.

**Comment by mf59816** [comment]
Rebased to tip of lens branch.  I'll post the criterion figures in a moment.

**Comment by mf59816** [comment]
```
before (lens branch)
====================

benchmarking parsing/Network.URI.parseURI
time                 6.649 μs   (6.638 μs .. 6.661 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 6.680 μs   (6.655 μs .. 6.740 μs)
std dev              121.2 ns   (58.54 ns .. 220.3 ns)
variance introduced by outliers: 17% (moderately inflated)

benchmarking parsing/URI.ByteString.parseURI strict
time                 2.244 μs   (2.235 μs .. 2.255 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.234 μs   (2.229 μs .. 2.248 μs)
std dev              26.89 ns   (14.04 ns .. 49.38 ns)

benchmarking parsing/URI.ByteString.parseURI lax
time                 2.355 μs   (2.349 μs .. 2.363 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.371 μs   (2.362 μs .. 2.383 μs)
std dev              34.15 ns   (24.31 ns .. 44.56 ns)
variance introduced by outliers: 13% (moderately inflated)

benchmarking serializing/URI.ByteString.serializeURI
time                 1.838 μs   (1.836 μs .. 1.841 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 1.844 μs   (1.839 μs .. 1.852 μs)
std dev              20.23 ns   (13.17 ns .. 30.57 ns)

Benchmark bench: FINISH


after (this branch)
===================

benchmarking parsing/Network.URI.parseURI
time                 6.727 μs   (6.693 μs .. 6.759 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 6.708 μs   (6.676 μs .. 6.744 μs)
std dev              116.2 ns   (103.7 ns .. 135.5 ns)
variance introduced by outliers: 16% (moderately inflated)

benchmarking parsing/URI.ByteString.parseURI strict
time                 2.314 μs   (2.303 μs .. 2.328 μs)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 2.371 μs   (2.342 μs .. 2.422 μs)
std dev              129.5 ns   (94.12 ns .. 172.2 ns)
variance introduced by outliers: 68% (severely inflated)

benchmarking parsing/URI.ByteString.parseURI lax
time                 2.440 μs   (2.400 μs .. 2.510 μs)
                     0.996 R²   (0.991 R² .. 1.000 R²)
mean                 2.442 μs   (2.422 μs .. 2.489 μs)
std dev              100.7 ns   (36.81 ns .. 201.6 ns)
variance introduced by outliers: 55% (severely inflated)

benchmarking parsing/URI.ByteString.parseRelativeRef strict
time                 1.540 μs   (1.513 μs .. 1.580 μs)
                     0.998 R²   (0.997 R² .. 1.000 R²)
mean                 1.523 μs   (1.516 μs .. 1.539 μs)
std dev              34.43 ns   (18.41 ns .. 66.04 ns)
variance introduced by outliers: 27% (moderately inflated)

benchmarking parsing/URI.ByteString.parseRelativeRef lax
time                 1.694 μs   (1.672 μs .. 1.729 μs)
                     0.997 R²   (0.995 R² .. 0.999 R²)
mean                 1.730 μs   (1.705 μs .. 1.763 μs)
std dev              90.62 ns   (78.00 ns .. 106.1 ns)
variance introduced by outliers: 67% (severely inflated)

benchmarking serializing/URI.ByteString.serializeURI
time                 1.960 μs   (1.892 μs .. 2.059 μs)
                     0.986 R²   (0.977 R² .. 0.996 R²)
mean                 1.949 μs   (1.899 μs .. 2.041 μs)
std dev              221.4 ns   (145.7 ns .. 334.0 ns)
variance introduced by outliers: 91% (severely inflated)

benchmarking serializing/URI.ByteString.serializeRelativeRef
time                 1.704 μs   (1.692 μs .. 1.714 μs)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 1.715 μs   (1.698 μs .. 1.744 μs)
std dev              69.19 ns   (32.61 ns .. 120.1 ns)
variance introduced by outliers: 54% (severely inflated)

Benchmark bench: FINISH
```

**Comment by mf59816** [comment]
If you want to be really picky about it, you may be worried about section 4.2 in the rfc:

```
   A path segment that contains a colon character (e.g., "this:that")
   cannot be used as the first segment of a relative-path reference, as
   it would be mistaken for a scheme name.  Such a segment must be
   preceded by a dot-segment (e.g., "./this:that") to make a relative-
   path reference.
```

In contrast to that:

```haskell
x = toLazyByteString . serializeRelativeRef $ RelativeRef
    Nothing "./this:that/wef/eofij" (Query [("1", "2")]) Nothing
y = parseRelativeRef laxURIParserOptions $ cs x
```

`y` evaluates to `Left (OtherError "Failed reading: mzero")`.  Without the `./`, parsing fails as specified in the RFC.  (`cs` is from string-conversions.)

Please let me know if you want me to look into it.  I personally could happily live with this.

**Comment by MichaelXavier** [comment]
I think we should try to take the high road here if possible. Since this library makes a point of being an RFC-compliant parser, we should stick to it. If you wouldn't mind trying to get this to conform to the spec that would be great. If it looks to hairy let me know and I'll give it a try.

**Comment by mf59816** [comment]
I knew I shouldn't have brought it up.  ;-)

Then again, fixing this obscure corner case made me discover that rootless relative refs were still broken.  That I would have minded soon.

**Comment by mf59816** [comment]
I think this is ready.

(Would you consider including this in release 0.1?  When can I hope to see that on hackage?  You've been very helpful and responsive, and I hope I'm not being impatient now.  I'd just like to make plans.  Thanks!)

**Comment by MichaelXavier** [comment]
This looks great! Thanks for digging into the edge cases. I'll cut a release and add you to the contributors. Really appreciate it!

**Comment by MichaelXavier** [comment]
Welp it looks like hackage is rejecting package with -Werror flags so I'm going to try to get that sorted out with them. Really annoying. I recommend installing this locally if you need something right away. If I can't get any progress on it, i'll just take off the flags for the release I guess.

**Comment by MichaelXavier** [comment]
Rather than trying to fight the law and fix cabal and hackage before uploading, I nixed the error flag, built and uploaded it. 0.1 is up.

**Comment by mf59816** [comment]
great.  thanks!  that was fun  (-:

(Found your fight with the law; for reference: https://github.com/haskell/hackage-server/issues/259.)

**Pull request merged**
