### PR TITLE
URI literals via QuasiQuotes

### PR DESCRIPTION
**Pull request by reactormonk**
Compiles locally, not sure how to make it backwards-compatible as well.

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Is that lower bound on template-haskell absolutely necessary? The test failure seem to be related to that.

Also I'm not sure what this buys the end user practically speaking. Would it give compile-time errors for staticallly-known URIs (and thus guaranteed correct URIs if it compiles)? Like `mkPathRel` and friends from the `path` library?

**Comment by reactormonk** [comment]
Some packages are [not even there with lts-2](https://travis-ci.org/Soostone/uri-bytestring/jobs/200134552#L230). Not sure how to handle this.

And yes, as described in the docs, `[uri|http://stackage.org|]` gives you a `UriRef a`.

**Comment by MichaelXavier** [comment]
I could see the value in this and the dependencies added don't look too burdensome.

So you have 2 options I think:

1. Try lowering the min bounds on these packages and see if they build on lts-2. You can test locally with `stack test --stack-yaml=stack-lts-2.yaml`. If the package isn't included in that lts, you can add it to the `extra-deps` section of that file.
2. If the lower bound can't go down any further and its not working on an lts, I think you can still specify a known working version in `extra-deps` in the relevant file. Those old ltses are never going to get updated with this new version of uri-bytestring so really what we're doing with this route is just proving that the package can be built on older GHC versions.

**Comment by reactormonk** [comment]
No, just doesn't work with < 7.8 - https://github.com/mboes/th-lift/commit/cd382e016339cd5d5dbe55edf78a1027020736c0

**Comment by reactormonk** [comment]
Should work.

**Comment by MichaelXavier** [comment]
@ozataman Any objections?

**Comment by MichaelXavier** [comment]
Released as 0.2.3.0. Thanks!

**Pull request merged**
