### PR TITLE
Compatibility with MonadFail proposal

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by MichaelXavier** [comment]
@bgamari I've been trying to work with what you gave me and get the test suites green. I've [cloned](https://github.com/Soostone/uri-bytestring/tree/bgamari-master) your branch over to this repo. I'm having some trouble in some of the older LTSes because while fail is available in them, attoparsec didn't start using fail until 0.13.1.0, so your generalized newtype deriving doesn't work in those cases.

What's the right thing to do? Should we set a lower bound of attoparsec >= 0.13.1.0 or is there another solution that I'm not seeing yet?

**Comment by lpsmith** [comment]
Couldn't you give up on generalized newtype deriving for the `MonadFail` instance,  and use CPP to handle older attoparsecs?

**Comment by bgamari** [comment]
As @lpsmith suggests, I suspect it would be pretty easy to implement the instance by hand with proper CPP guards.

**Comment by MichaelXavier** [comment]
@lpsmith @bgamari Can you check the state of [the diff](https://github.com/Soostone/uri-bytestring/compare/bgamari-master?expand=1) and let me know if I've done things correctly? The test suite is green across the board including into nightlies.

**Comment by bgamari** [comment]
Looks reasonable to me. Thanks for picking this up, @MichaelXavier!

**Comment by MichaelXavier** [comment]
Thanks folks! I'll get a release out soon.

**Pull request merged**
