### PR TITLE
Use lightweight lens-simple instead of lens

### PR DESCRIPTION
**Pull request by k0ral**
Should I defend this change ? :)

### CODE REVIEW

**Comment by MichaelXavier** [comment]
What's the motivation? Shorter setup time for running tests?

**Comment by k0ral** [comment]
Precisely.

**Comment by MichaelXavier** [comment]
I guess I don't particularly care all that much since I'm using stack but as long as its equivalent with what is needed in the tests, its fine. You may need to rebase from master though, the tests are failing.

**Comment by k0ral** [comment]
Actually, the error comes from missing import of NFData, unrelated to my code. I've fixed it anyway.

**Comment by MichaelXavier** [comment]
Thanks!

**Comment by ozataman** [comment]
A bit after the fact, but I'll add a +1 to the general principle of
minimizing dependencies as much as possible. Lens is particularly large, so
this makes sense to me too, assuming we don't lose any capability in the
process.


*Ozgun Ataman*

CEO
*Soostone Inc.*
25 Broadway, 9th Floor
New York, NY, 10004

+1 917 725 0849 (Office)
+1 734 262 0676 (Mobile)
+1 212 320 0251 (Fax)
ozgun.ataman@soostone.com

**Comment by MichaelXavier** [comment]
@ozataman agreed, however this is a bit of a special case since its just the test suite that brings in lens. But yeah since we only use the simplest lens functions that are covered by lens-simple, using lens-simple as a lightweight shim doesn't have a downside.

**Pull request merged**
